In [2]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([0, 1, 3, 4, 5, 6, 7, 8, 9, 10])
np.mean(a)

5.3

In [5]:
### Create a rank-1 numpy array with 1 axes of length 3.
a = np.array([1, 2, 3])

### Print object type
print('type(a) =', type(a))

### Print shape
print("na.shape =", a.shape)

### Print some values in a
print("\nValues in a: ", a[0], a[1], a[2])

### Create a 2x2 numpy array
b = np.array([[1, 2], [3, 4]])

### Print shape
print("\nb.shape =", b.shape)

## Print some values in b
print("\nValues in b: ", b[0, 0], b[0, 1], b[1, 1])


### Create a 3x2 numpy array
c = np.array([[1, 2], [3, 4], [5, 6]])

### Print shape
print("\nc.shape =", c.shape)

### Print some values in c
print("\nValues in c: ", c[0, 1], c[1, 0], c[2, 0], c[2, 1])

type(a) = <class 'numpy.ndarray'>
na.shape = (3,)

Values in a:  1 2 3

b.shape = (2, 2)

Values in b:  1 2 4

c.shape = (3, 2)

Values in c:  2 3 5 6


In [6]:
### 2x3 array containing zeros
d = np.zeros((2, 3))
print("d =\n", d)

### 4x2 array of ones
e = np.ones((4, 2))
print("\ne =\n", e)

### 2x2 constant array
f = np.full((2, 2), 9)
print("\nf =\n", f)

### 3x3 random array
g = np.random.random((3, 3))
print("\ng =\n", g)

### 2x2 array with uninitialized values
h = np.empty((2, 2))
print("\nh =\n", h)

d =
 [[0. 0. 0.]
 [0. 0. 0.]]

e =
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

f =
 [[9 9]
 [9 9]]

g =
 [[0.92387596 0.41851489 0.85224397]
 [0.47729803 0.89371823 0.10232178]
 [0.19035318 0.79244331 0.9152751 ]]

h =
 [[1.13930326e-313 0.00000000e+000]
 [2.12199579e-314 9.52502085e-307]]


In [7]:
### Create 3x4 array

h = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("h=\n", h)

### Slice array to make a 2x2 sub-array
i = h[:2, 1: 3]

print("\ni=\n", i)

print("\nh[0, 1] =", h[0, 1])

### Modify the slice
i[0, 0] = 1738

### Print to show how modifying the slice also changes the base object
print("\nh[0, 1] =", h[0, 1])

h=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

i=
 [[2 3]
 [6 7]]

h[0, 1] = 2

h[0, 1] = 1738


In [8]:
h = np.zeros((3, 3))

i = h[0: 2, 0: 2].copy()
h[0, 0] = 99
print("h =\n", h)
print("\ni =\n", i)

h =
 [[99.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

i =
 [[0. 0.]
 [0. 0.]]


In [10]:
### Integer
j = np.array([1, 2])
print(j.dtype)

### Float
k = np.array([1.0, 2.0])
print(k.dtype)

### Force Data Type
l = np.array([1.0, 2.0], dtype=np.int64)
print(l.dtype)

int64
float64
int64


In [12]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype =np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print("x + y =\n", x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print("\nx - y =\n", x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print("\nx * y =\n", x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print("\nx / y =\n", x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("\nsqrt(x) =\n", np.sqrt(x))

x + y =
 [[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

x - y =
 [[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

x * y =
 [[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

x / y =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

sqrt(x) =
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [13]:
x = np.array([[1, 2,], [3, 4]])
print("x =\n", x)

### Compute sum of all elements; prints "10"
print("\nsum(x) =", np.sum(x))

### Compute sum of each column; prints "[4 6]"
print("sum(x, axis=0) =", np.sum(x, axis = 0))

### Compute sum of each row; prints "[3 7]"
print("sum(x, axis=1) =", np.sum(x, axis = 1))

x =
 [[1 2]
 [3 4]]

sum(x) = 10
sum(x, axis=0) = [4 6]
sum(x, axis=1) = [3 7]


In [14]:
x = np.array([[1, 2], [3, 4]])
print("x =\n", x)

### Compute mean of all elements; prints "2.5"
print("\nmean(x) =", np.mean(x))

### Compute mean of each column; prints "[2 3]"
print("mean(x, axis=0) =", np.mean(x, axis=0))

### Compute mean of each row; prints "[1.5 3.5]"
print("mean(x, axis=1) =", np.mean(x, axis=1))

x =
 [[1 2]
 [3 4]]

mean(x) = 2.5
mean(x, axis=0) = [2. 3.]
mean(x, axis=1) = [1.5 3.5]


### Importing data

In [2]:
import pandas as pd

In [3]:
# The file name string that holds our .csv file
fname = "/content/drive/MyDrive/weather/Cartwheeldata.csv"

# Read the .csv file and store it as a Pandas Data Frame
df = pd.read_csv(fname)

# Print the object type
type(df)

pandas.core.frame.DataFrame

### Viewing data

In [4]:
df.head()

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1   56      F            1       Y             1    62.0      61.0   
1   2   26      F            1       Y             1    62.0      60.0   
2   3   33      F            1       Y             1    66.0      64.0   
3   4   39      F            1       N             0    64.0      63.0   
4   5   27      M            2       N             0    73.0      75.0   

   CWDistance Complete  CompleteGroup  Score  
0          79        Y              1      7  
1          70        Y              1      8  
2          85        Y              1      7  
3          87        Y              1     10  
4          72        N              0      4

In [6]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [7]:
df.dtypes

ID                 int64
Age                int64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup      int64
Score              int64
dtype: object

In [8]:
# Return all observations of the variable CWDistance
df.loc[: "CWDistance"]

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0    1   56      F            1       Y             1   62.00      61.0   
1    2   26      F            1       Y             1   62.00      60.0   
2    3   33      F            1       Y             1   66.00      64.0   
3    4   39      F            1       N             0   64.00      63.0   
4    5   27      M            2       N             0   73.00      75.0   
5    6   24      M            2       N             0   75.00      71.0   
6    7   28      M            2       N             0   75.00      76.0   
7    8   22      F            1       N             0   65.00      62.0   
8    9   29      M            2       Y             1   74.00      73.0   
9   10   33      F            1       Y             1   63.00      60.0   
10  11   30      M            2       Y             1   69.50      66.0   
11  12   28      F            1       Y             1   62.75      58.0   
12  13   25      F            1       Y             1   65.00      64.5   
13  14   23      F            1       N             0   61.50      57.5   
14  15   31      M            2       Y             1   73.00      74.0   
15  16   26      M            2       Y             1   71.00      72.0   
16  17   26      F            1       N             0   61.50      59.5   
17  18   27      M            2       N             0   66.00      66.0   
18  19   23      M            2       Y             1   70.00      69.0   
19  20   24      F            1       Y             1   68.00      66.0   
20  21   23      M            2       Y             1   69.00      67.0   
21  22   29      M            2       N             0   71.00      70.0   
22  23   25      M            2       N             0   70.00      68.0   
23  24   26      M            2       N             0   69.00      71.0   
24  25   23      F            1       Y             1   65.00      63.0   

    CWDistance Complete  CompleteGroup  Score  
0           79        Y              1      7  
1           70        Y              1      8  
2           85        Y              1      7  
3           87        Y              1     10  
4           72        N              0      4  
5           81        N              0      3  
6          107        Y              1     10  
7           98        Y              1      9  
8          106        N              0      5  
9           65        Y              1      8  
10          96        Y              1      6  
11          79        Y              1     10  
12          92        Y              1      6  
13          66        Y              1      4  
14          72        Y              1      9  
15         115        Y              1      6  
16          90        N              0     10  
17          74        Y              1      5  
18          64        Y              1      3  
19          85        Y              1      8  
20          66        N              0      2  
21         101        Y              1      8  
22          82        Y              1      4  
23          63        Y              1      5  
24          67        N              0      3

In [11]:
df.CWDistance

0      79
1      70
2      85
3      87
4      72
5      81
6     107
7      98
8     106
9      65
10     96
11     79
12     92
13     66
14     72
15    115
16     90
17     74
18     64
19     85
20     66
21    101
22     82
23     63
24     67
Name: CWDistance, dtype: int64

In [12]:
df.loc[:, ["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0           79   62.00      61.0
1           70   62.00      60.0
2           85   66.00      64.0
3           87   64.00      63.0
4           72   73.00      75.0
5           81   75.00      71.0
6          107   75.00      76.0
7           98   65.00      62.0
8          106   74.00      73.0
9           65   63.00      60.0
10          96   69.50      66.0
11          79   62.75      58.0
12          92   65.00      64.5
13          66   61.50      57.5
14          72   73.00      74.0
15         115   71.00      72.0
16          90   61.50      59.5
17          74   66.00      66.0
18          64   70.00      69.0
19          85   68.00      66.0
20          66   69.00      67.0
21         101   71.00      70.0
22          82   70.00      68.0
23          63   69.00      71.0
24          67   65.00      63.0

In [13]:
df[["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0           79   62.00      61.0
1           70   62.00      60.0
2           85   66.00      64.0
3           87   64.00      63.0
4           72   73.00      75.0
5           81   75.00      71.0
6          107   75.00      76.0
7           98   65.00      62.0
8          106   74.00      73.0
9           65   63.00      60.0
10          96   69.50      66.0
11          79   62.75      58.0
12          92   65.00      64.5
13          66   61.50      57.5
14          72   73.00      74.0
15         115   71.00      72.0
16          90   61.50      59.5
17          74   66.00      66.0
18          64   70.00      69.0
19          85   68.00      66.0
20          66   69.00      67.0
21         101   71.00      70.0
22          82   70.00      68.0
23          63   69.00      71.0
24          67   65.00      63.0

In [14]:
df.loc[:9, ["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0          79    62.0      61.0
1          70    62.0      60.0
2          85    66.0      64.0
3          87    64.0      63.0
4          72    73.0      75.0
5          81    75.0      71.0
6         107    75.0      76.0
7          98    65.0      62.0
8         106    74.0      73.0
9          65    63.0      60.0

In [15]:
df.loc[10: 15]

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
10  11   30      M            2       Y             1   69.50      66.0   
11  12   28      F            1       Y             1   62.75      58.0   
12  13   25      F            1       Y             1   65.00      64.5   
13  14   23      F            1       N             0   61.50      57.5   
14  15   31      M            2       Y             1   73.00      74.0   
15  16   26      M            2       Y             1   71.00      72.0   

    CWDistance Complete  CompleteGroup  Score  
10          96        Y              1      6  
11          79        Y              1     10  
12          92        Y              1      6  
13          66        Y              1      4  
14          72        Y              1      9  
15         115        Y              1      6

In [16]:
df.loc[:9, "CWDistance"]

0     79
1     70
2     85
3     87
4     72
5     81
6    107
7     98
8    106
9     65
Name: CWDistance, dtype: int64

In [17]:
df.iloc[: 4]

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1   56      F            1       Y             1    62.0      61.0   
1   2   26      F            1       Y             1    62.0      60.0   
2   3   33      F            1       Y             1    66.0      64.0   
3   4   39      F            1       N             0    64.0      63.0   

   CWDistance Complete  CompleteGroup  Score  
0          79        Y              1      7  
1          70        Y              1      8  
2          85        Y              1      7  
3          87        Y              1     10

In [18]:
df.iloc[1: 5, 2: 4]

Gender  GenderGroup
1      F            1
2      F            1
3      F            1
4      M            2

In [30]:
df.iloc[1:5, :][["Gender", "GenderGroup"]]

Gender  GenderGroup
1      F            1
2      F            1
3      F            1
4      M            2

In [31]:
df.dtypes

ID                 int64
Age                int64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup      int64
Score              int64
dtype: object

In [21]:
print("stubborn puppies never accept themself mummy please please i request you ignore them they are just waist of time")

stubborn puppies never accept themself mummy please please i request you ignore them they are just waist of time


In [22]:
print("stubborn puppies never accept themself mummy please please i request you ignore them they are just waist of time")

stubborn puppies never accept themself mummy please please i request you ignore them they are just waist of time


In [24]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [25]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [26]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [27]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [28]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [29]:
print("stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time")
print("And They Just waisting your time there is no need bet or bets to talk to dogs")

stubborn puppies never accept themself as a mother please please i request you ignore them they are just waist of time
And They Just waisting your time there is no need bet or bets to talk to dogs


In [32]:
# List unique values in the df['Gender'] column
df["Gender"].unique()

array(['F', 'M'], dtype=object)

In [33]:
df["GenderGroup"].unique()

array([1, 2])

In [34]:
df[["Gender", "GenderGroup"]]

Gender  GenderGroup
0       F            1
1       F            1
2       F            1
3       F            1
4       M            2
5       M            2
6       M            2
7       F            1
8       M            2
9       F            1
10      M            2
11      F            1
12      F            1
13      F            1
14      M            2
15      M            2
16      F            1
17      M            2
18      M            2
19      F            1
20      M            2
21      M            2
22      M            2
23      M            2
24      F            1

In [35]:
pd.crosstab(df["Gender"], df["GenderGroup"])

GenderGroup   1   2
Gender             
F            12   0
M             0  13

In [36]:
df.groupby(['Gender', 'GenderGroup']).size()

Gender  GenderGroup
F       1              12
M       2              13
dtype: int64

Again, the output indicates that we have two combinations:

* Case 1: Gender = F & Gender Group = 1
* Case 2: Gender = M & GenderGroup = 2.